"""initial schema

Revision ID: 385a8e793b2b
Revises:
Create Date: 2026-09-12 15:30:18.219974

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "385a8e793b2b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("smtp_host", sa.String(length=300), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=300), nullable=True),
        sa.Column("encrypted_password", sa.Text(), nullable=True),
        sa.Column("from_email", sa.String(length=300), nullable=False),
        sa.Column("from_name", sa.String(length=200), nullable=False),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.Column("security", sa.String(length=20), nullable=False),
        sa.Column("subject_prefix", sa.String(length=120), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("protocol", sa.String(length=40), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("supports_json_mode", sa.Boolean(), nullable=False),
        sa.Column("extra_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_llm_profiles_is_default"), "llm_profiles", ["is_default"], unique=False
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arxiv_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("authors", sa.JSON(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("primary_category", sa.String(length=40), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("abs_url", sa.String(length=500), nullable=False),
        sa.Column("pdf_url", sa.String(length=500), nullable=False),
        sa.Column("doi", sa.String(length=200), nullable=True),
        sa.Column("journal_ref", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_starred", sa.Boolean(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("personal_notes", sa.Text(), nullable=True),
        sa.Column("user_tags", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_papers_arxiv_id"), "papers", ["arxiv_id"], unique=True)
    op.create_index(op.f("ix_papers_decision"), "papers", ["decision"], unique=False)
    op.create_index(op.f("ix_papers_first_seen_at"), "papers", ["first_seen_at"], unique=False)
    op.create_index(op.f("ix_papers_is_read"), "papers", ["is_read"], unique=False)
    op.create_index(op.f("ix_papers_is_starred"), "papers", ["is_starred"], unique=False)
    op.create_index(
        op.f("ix_papers_primary_category"), "papers", ["primary_category"], unique=False
    )
    op.create_index(op.f("ix_papers_published_at"), "papers", ["published_at"], unique=False)
    op.create_table(
        "run_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("trigger", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("topics_processed", sa.Integer(), nullable=False),
        sa.Column("papers_found", sa.Integer(), nullable=False),
        sa.Column("papers_new", sa.Integer(), nullable=False),
        sa.Column("analyses_completed", sa.Integer(), nullable=False),
        sa.Column("analyses_failed", sa.Integer(), nullable=False),
        sa.Column("emails_sent", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_logs_started", "run_logs", ["started_at"], unique=False)
    op.create_index(
        "uq_running_job_type",
        "run_logs",
        ["job_type"],
        unique=True,
        sqlite_where=sa.text("status = 'running'"),
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "schedule_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("digest_language", sa.String(length=20), nullable=False),
        sa.Column("public_base_url", sa.String(length=500), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("relevance_prompt", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_results", sa.Integer(), nullable=False),
        sa.Column("lookback_days", sa.Integer(), nullable=False),
        sa.Column("analyze_pdf", sa.Boolean(), nullable=False),
        sa.Column("llm_profile_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["llm_profile_id"], ["llm_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_enabled"), "topics", ["enabled"], unique=False)
    op.create_index(op.f("ix_topics_name"), "topics", ["name"], unique=True)
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("llm_profile_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("source_mode", sa.String(length=20), nullable=False),
        sa.Column("paper_version", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("research_question", sa.Text(), nullable=True),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=True),
        sa.Column("experiments", sa.Text(), nullable=True),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("reading_advice", sa.Text(), nullable=True),
        sa.Column("relevance_reason", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("rigor_score", sa.Float(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["llm_profile_id"], ["llm_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analyses_paper_created", "analyses", ["paper_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_analyses_status"), "analyses", ["status"], unique=False)
    op.create_index(
        "ix_analyses_topic_created", "analyses", ["topic_id", "created_at"], unique=False
    )
    op.create_table(
        "topic_papers",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "paper_id"),
        sa.UniqueConstraint("topic_id", "paper_id", name="uq_topic_paper"),
    )
    op.create_index("ix_topic_papers_discovered", "topic_papers", ["discovered_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_topic_papers_discovered", table_name="topic_papers")
    op.drop_table("topic_papers")
    op.drop_index("ix_analyses_topic_created", table_name="analyses")
    op.drop_index(op.f("ix_analyses_status"), table_name="analyses")
    op.drop_index("ix_analyses_paper_created", table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_topics_name"), table_name="topics")
    op.drop_index(op.f("ix_topics_enabled"), table_name="topics")
    op.drop_table("topics")
    op.drop_table("schedule_settings")
    op.drop_index(
        "uq_running_job_type",
        table_name="run_logs",
        sqlite_where=sa.text("status = 'running'"),
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_run_logs_started", table_name="run_logs")
    op.drop_table("run_logs")
    op.drop_index(op.f("ix_papers_published_at"), table_name="papers")
    op.drop_index(op.f("ix_papers_primary_category"), table_name="papers")
    op.drop_index(op.f("ix_papers_is_starred"), table_name="papers")
    op.drop_index(op.f("ix_papers_is_read"), table_name="papers")
    op.drop_index(op.f("ix_papers_first_seen_at"), table_name="papers")
    op.drop_index(op.f("ix_papers_decision"), table_name="papers")
    op.drop_index(op.f("ix_papers_arxiv_id"), table_name="papers")
    op.drop_table("papers")
    op.drop_index(op.f("ix_llm_profiles_is_default"), table_name="llm_profiles")
    op.drop_table("llm_profiles")
    op.drop_table("email_settings")
    # ### end Alembic commands ###
